const movies = [
  {
    naziv: "Pulp fiction",
    zanr: "Crime",
    godina: 1994,
    coverSlika: "",
    glumci: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
  },
  {
    naziv: "About Time",
    zanr: "Drama",
    godina: 2013,
    coverSlika: "",
    glumci: ["Domhnall Gleeson", "Rachel McAdams", "Bill Nighy"],
  },
  {
    naziv: "The Shawshank Redemption",
    zanr: "Drama",
    godina: 1994,
    coverSlika: "",
    glumci: ["Tim Robbins", "Morgan Freeman"],
  },
  {
    naziv: "Fight club",
    zanr: "Drama",
    godina: 1999,
    coverSlika: "",
    glumci: ["Brad Pitt", "Edward Norton"],
  },
  {
    naziv: "Inception",
    zanr: "Action",
    godina: 2010,
    coverSlika: "",
    glumci: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
  },
  {
    naziv: "One Flew Over the Cuckoo’s Nest",
    zanr: "Drama",
    godina: 1975,
    coverSlika: "",
    glumci: ["Jack Nicholson", "Louise Fletcher"],
  },
  {
    naziv: "The Silence of the Lambs",
    zanr: "Crime",
    godina: 1991,
    coverSlika: "",
    glumci: ["Jodie Foster", "Anthony Hopkins"],
  },
  {
    naziv: "Sinister",
    zanr: "Horror",
    godina: 2012,
    coverSlika: "",
    glumci: ["Ethan Hawke", "Juliet Rylance"],
  },
  {
    naziv: "Insidious",
    zanr: "Horror",
    godina: 2010,
    coverSlika: "",
    glumci: ["Patrick Wilson", "Rose Byrne", "Lin Shaye"],
  },
  {
    naziv: "Untouchable",
    zanr: "Biography",
    godina: 2011,
    coverSlika: "",
    glumci: ["Francois Cluzet", "Omar Sy"],
  },
  {
    naziv: "The Dark Knight Rises",
    zanr: "Action",
    godina: 2012,
    coverSlika: "",
    glumci: ["Christian Bale", "Tom Hardy"],
  },
  {
    naziv: "Avengers:Endgame",
    zanr: "Action",
    godina: 2019,
    coverSlika: "",
    glumci: ["Robert Downey Jr", "Chris Evans", "Mark Ruffalo"],
  },
  {
    naziv: "Good Will Hunting",
    zanr: "Drama",
    godina: 1997,
    coverSlika: "",
    glumci: ["Robin Williams", "Matt Damon", "Ben Affleck"],
  },
  {
    naziv: "The Hunt",
    zanr: "Drama",
    godina: 1997,
    coverSlika: "",
    glumci: ["Robin Williams", "Matt Damon", "Ben Affleck"],
  },
  {
    naziv: "Amelie",
    zanr: "Comedy",
    godina: 2001,
    coverSlika: "",
    glumci: ["Audrey Tautou", "Mathieu Kassovitz"],
  },
  {
    naziv: "Shutter Island",
    zanr: "Mystery",
    godina: 2010,
    coverSlika: "",
    glumci: ["Leonardo DiCaprio", "Mark Ruffalo"],
  },
  {
    naziv: "Joker",
    zanr: "Crime",
    godina: 2019,
    coverSlika: "",
    glumci: ["Joaquin Phoenix", "Robert De Niro"],
  },
  {
    naziv: "The Departed",
    zanr: "Crime",
    godina: 2006,
    coverSlika: "",
    glumci: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
  },
];
